image: docker:latest

variables:
  IMAGE_NAME: "ci.perditum.com/perditum/account-rs"
  IMAGE_TAG: "${CI_COMMIT_REF_SLUG}"

before_script:
  - git submodule update --init
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" ci.perditum.com

stages:
  - build

build_and_push:
  stage: build
  script:
    - echo "DATABASE_URL=$DATABASE_URL" > .env
    - docker build -t "$IMAGE_NAME:$IMAGE_TAG" .
    - |
      if [ "$CI_COMMIT_REF_NAME" = "main" ]; then
        docker tag "$IMAGE_NAME:$IMAGE_TAG" "$IMAGE_NAME:latest"
        docker push "$IMAGE_NAME:latest"
      else
        echo "skipping push"
      fi
